apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "py_fastapi_poetry.fullname" . }}
  labels:
    {{- include "py_fastapi_poetry.labels" . | nindent 4 }}
data:
  env: |
    SQL_DB_SERVER="{{ .Release.Name }}-mysql"
    SQL_DB_PORT=3306
    SQL_DB_USER="root"
    SQL_DB_PASSWORD="admin"
    SQL_DB_SCHEMA="python_test"

    REDIS_DB_SERVER="{{ .Release.Name }}-redis-master"
    REDIS_DB_PORT=6379
    REDIS_DB_NUMBER=0