name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  # Docker username
  USERNAME: ${{ github.actor }}
  # Docker password
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Show environment variables
      run: echo ${{ env.USERNAME }} ${{ env.PASSWORD }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag python_fastapi_poetry:$(date +%s)
    - name: List docker images
      run: docker images
    - name: Docker login
      run: docker login -u ${{ env.USERNAME }} -p -u ${{ env.PASSWORD }}
      
