name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  # Docker username
  USERNAME: ${{ github.actor }}
  # Docker password
  PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Show all environment variables
      run: env ; echo ${{ var.VARIABLE }}; echo ${{ var.SECRET }}
    - name: Show environment variables
      run: echo ${{ env.USERNAME }} ${{ env.PASSWORD }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file deploy/docker/Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%Y%m%d)
    - name: List docker images
      run: docker images
    - name: Docker login
      run: docker login -u ${{ env.USERNAME }} -p ${{ env.PASSWORD }}
    - name: Docker push
      run: docker push ${{ env.IMAGE_NAME }}:$(date +%Y%m%d)
    - name: Docker push latest version
      run: docker tag ${{ env.IMAGE_NAME }}:$(date +%Y%m%d) ${{ env.IMAGE_NAME }}:latest ; docker push ${{ env.IMAGE_NAME }}:latest
      
